### ISSUE TITLE
Website/Community intentions

### ISSUE THREAD

**Issue by patdavid** [gctechevents/gctechevents.github.io#2]
I'm not sure this is the best place for this, but I have some questions about the overall intentions for the site and community building.

Is this portal intended to be the primary branding and nexus for a community based around Gulf Coast technologists?

* Specific technologies?
  * Languages?
  * OS?
  * Programming?
  * Other?
* Overall Gulf Coast tech-related community?
  Should this reach out to, and include, other types of tech-related communities or maker-spaces that are out there?

I have other thoughts and questions, but I think a means for communication between interested parties in helping out would be a good first step.  It _can_ be here for now if needed, or could be a forum, slack, irc, I don't really care. 😄 Just some means to capture involvement, ideas, suggestions, and general administrative stuff for building a community. 
(sorry, community-building is something I do so I immediately start down this path).

**Comment by zhangxd6** [comment]
sent you invitation of our slack
